#sdk: "/Users/adiaz/.rvm/gems/ruby-1.9.3-p194/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: rodar_client
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rodarclient
  BundleURLScheme: rodarclient
wp:
  productid: '27716cf0-a1cf-012f-9c9e-406c8f07c2cc'
symbian:
  uid: '0xe19e6462'
android:
  version: 4.0.3
capabilities:
  - camera
extensions: ["json", "another-extension"]
