source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'haml-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'quiet_assets'
end

group :development do
  gem 'hirb'
end

gem 'jquery-rails'
gem 'rhoconnect-rb'
gem 'bootstrap-sass'
gem 'haml'
gem 'thin'
